### ISSUE TITLE
InexactError when running @benchmark

### ISSUE THREAD

**Issue by mjulian31** [JuliaCI/BenchmarkTools.jl#207] opened 2021-05-07 01:20 UTC
The stack trace is:
<img width="948" alt="Screen Shot 2021-05-06 at 9 18 28 PM" src="https://user-images.githubusercontent.com/35236176/117384328-b6d7b880-aeb0-11eb-958b-4ba6aab2ab7c.png">

The test is run from:
<img width="725" alt="Screen Shot 2021-05-06 at 9 16 24 PM" src="https://user-images.githubusercontent.com/35236176/117384367-c6ef9800-aeb0-11eb-8908-e5c0562ae33d.png">

And the code that is being benchmarked:
<img width="449" alt="Screen Shot 2021-05-06 at 9 17 05 PM" src="https://user-images.githubusercontent.com/35236176/117384353-bfc88a00-aeb0-11eb-99c7-61e5e1eb5850.png">

The error is on GitHub actions with Julia 1.3 and 1.4 on ubuntu x86 machines only.

**Comment by jaakkor2** [comment] 2021-05-20 05:30
Duplicate of https://github.com/JuliaCI/BenchmarkTools.jl/issues/166 .

Changing `Int` to `Int64` in https://github.com/JuliaCI/BenchmarkTools.jl/blob/v1.0.0/src/execution.jl#L250 should help.

**Closed** 2021-07-28 09:35 UTC
