### ISSUE TITLE
Feature for just running the code without benchmarking

### ISSUE THREAD

**Issue by gaurav-arya** [JuliaCI/BenchmarkTools.jl#300] opened 2023-02-02 14:18 UTC
`BenchmarkTools.jl` has some special syntax for string interpolation, plus the `setup` block, etc. 

Often I'm `@btime`'ing something and then I just decide to run it once and simply remove the `@btime`, but this of course errors, and I need to revise it back to a version that doesn't use any special syntax. As a convenience, it would be nice to have a macro like `@runonce` which just runs the function once and gives the output, but accepts the special syntax.

**Comment by willow-ahrens** [comment] 2024-12-23 22:27
I'm going to close this for now as completed, please feel free to reopen if this did not resolve your issue. I'll also add that this is almost a duplicate of #118, which would be a good one to eventually fix.

**Closed** 2024-12-23 22:27 UTC
Labels: enhancement
