### ISSUE TITLE
Memory of interpolated variables is never freed

### ISSUE THREAD

**Issue by mfsch** [JuliaCI/BenchmarkTools.jl#214] opened 2021-05-25 17:45 UTC
This might be the intended behavior, but I’ve noticed that when running multiple benchmarks in a loop, the data of the variables that are interpolated into the benchmark accumulates until the system eventually runs out of memory. A simplified demonstration of this behavior:

```julia
function bmk()
    a = zeros(128*1024*1024) # 1GB
    b = @benchmarkable $a .+= 1
    run(b)
end
```

Repeated calls of this function each increase the memory usage of the Julia process by 1GB. My actual usage where I ran into this issue was a bit more complex, where I wanted to measure the performance of some of my functions for different problem sizes, including sizes that take up a major part of the system’s memory.

If this is the intended behavior, would it be possible to document it in the section about interpolated variables? And are there any workarounds other than starting a new Julia process for each problem size?

**Comment by vchuravy** [comment] 2021-07-28 10:11
Duplicate of #127 

I think the general feeling is that this is something that needs fixing, 
but no one had the time/energy yet

**Closed by vchuravy** 2021-07-28 10:11 UTC
